name: DellunaPostOffice
version: '${project.version}'
main: gaya.pe.kr.core.DellunaPostOffice
api-version: 1.18
authors: [ Gaya_Soft ]
description: 우편물 플러그인

commands:
  우편함:
    description: "우편함 명령어"
  우편보내기:
    description: "우편을 보내기 위한 명령어"